### ISSUE TITLE
circulation - błąd weryfikacji uprawnień

### ISSUE THREAD

**Issue by gmacike** [gmacike/sharehold#14]
Renata pomimo posiadania uprawnień nie widzi opcji menu umożliwiającej dodanie klienta, ani też przycisku do jego edycji.

**Comment by gmacike** [comment]
Jakiś komentarz? Jakaś naprawa?

**Comment by macku30** [comment]
Było naprawione przed ostatnią wersją, na obecnej produkcji już działa
